apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: djangoprom
  labels: 
    app: djangoprom
spec:
  endpoints:
  - port: metrics
    #path: /metrics
    #interval: 10s
    # scheme: http
  selector: 
    matchLabels: 
      app: djangoprom
  # namespaceSelector: 
  #   matchNames:
  #   - production