apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: {{ .Values.externalPostgres.postgresqlUsername | b64enc  }}
  password: {{ .Values.externalPostgres.postgresqlPassword | b64enc  }}
  db: {{ .Values.externalPostgres.postgresqlDatabase | b64enc }}